language: python
sudo: false
matrix:
  fast_finish: true
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7-dev

cache:
  pip: true
  directories:
    - .venv
    - $HOME/.cache/pypoetry
before_install:
  - pip install poetry --pre
  - poetry develop -v
script:
  - poetry run pytest tests/
