[tool.poetry]
name = "pyramid_openapi3"
version = "0.1.0"
description = "Pyramid plugin for openapi3 spec validation"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">3.4"
openapi-spec-validator = "^0.2.2"
openapi-core = "^0.5.0"
Werkzeug = "^0.14.1"
pyramid = "^1.9"

[tool.poetry.dev-dependencies]
coverage = "^4.5"
pytest = "^3.6"
